# Generated by Django 4.2.7 on 2023-11-21 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_descriptions_product_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='unit_price',
        ),
    ]
