# Generated by Django 4.2.7 on 2023-11-21 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_membership_type_customer_membership'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='place_at',
            new_name='placed_at',
        ),
    ]
