# Generated by Django 4.2.7 on 2023-11-21 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_place_at_order_placed_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='membership_type',
            new_name='payment_status',
        ),
    ]
