# Generated by Django 4.2.7 on 2023-11-21 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_membership_type_order_payment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='quatity',
            new_name='quantity',
        ),
    ]
