# Generated by Django 4.2.7 on 2023-11-21 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_rename_order_orderitem_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='order_id',
            new_name='order',
        ),
    ]
