# Generated by Django 4.2.7 on 2024-09-23 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_rename_order_id_orderitem_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['title']},
        ),
    ]
