# Generated by Django 4.2.7 on 2024-09-23 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_remove_collection_featured_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
